"""FROZEN CONTRACT — the shared state every agent reads and writes.

============================================================================
DO NOT EDIT THIS FILE without agreement from all 4 team members in the group
chat. Every module (agents, supervisor, UI, tests) depends on these keys.
If you need a new key: propose it, get 4 thumbs-up, then one PR updates
this file + CLAUDE.md together.
============================================================================

Rules:
- Each agent writes ONLY its own artifact keys (see the table in CLAUDE.md).
- List keys marked with `operator.add` are APPEND-ONLY: return new entries,
  never the whole list.
- `token_usage` uses the merge_usage reducer: return only your agent's delta,
  e.g. {"developer": {"input_tokens": 120, "output_tokens": 300, "cost_usd": 0.0002}}.
"""
import operator
from typing import Annotated, Dict, List, TypedDict

# Canonical agent names, in default pipeline order. Used by the supervisor,
# the UI status dashboard, and the mock outputs. Keep in sync everywhere.
AGENT_ORDER: List[str] = [
    "requirements_analyst",
    "architect",
    "developer",
    "reviewer",
    "tester",
    "doc_writer",
    "devops",
]

SUPERVISOR = "supervisor"
HUMAN = "human"  # used as from/to in agent_messages for HITL events


class AgentMessage(TypedDict):
    """One agent-to-agent (or agent-to-human) message. Shown in the UI's
    communication history tab."""
    from_agent: str
    to_agent: str
    content: str
    timestamp: str  # ISO 8601


class LogEntry(TypedDict):
    """One structured log line. Shown in the UI's execution log tab and also
    written to logs/run.log by src/observability/logging_setup.py."""
    timestamp: str
    agent: str
    level: str  # INFO | WARNING | ERROR
    message: str


def merge_usage(
    left: Dict[str, Dict[str, float]] | None,
    right: Dict[str, Dict[str, float]] | None,
) -> Dict[str, Dict[str, float]]:
    """Reducer: sums per-agent token usage deltas into the running totals."""
    merged: Dict[str, Dict[str, float]] = {k: dict(v) for k, v in (left or {}).items()}
    for agent, delta in (right or {}).items():
        current = merged.setdefault(
            agent, {"input_tokens": 0, "output_tokens": 0, "cost_usd": 0.0}
        )
        for key in ("input_tokens", "output_tokens", "cost_usd"):
            current[key] = current.get(key, 0) + delta.get(key, 0)
    return merged


class ProjectState(TypedDict, total=False):
    # ------------------------------------------------------------------ input
    project_request: str          # the user's plain-English project idea

    # ------------------------------------------------- supervisor (Member 1)
    next_agent: str               # who runs next, or "FINISH"
    supervisor_plan: str          # current plan / reasoning shown in the UI
    final_report: str             # composed at FINISH; shown in report viewer

    # ------------------------------------------------------------- artifacts
    requirements_doc: str         # requirements_analyst (Member 2)
    architecture_doc: str         # architect            (Member 2)
    code_files: Dict[str, str]    # developer            (Member 3)  path -> content
    review_feedback: str          # reviewer             (Member 3)
    review_approved: bool         # reviewer             (Member 3)
    test_report: str              # tester               (Member 3)
    tests_passed: bool            # tester               (Member 3)
    documentation: str            # doc_writer           (Member 2)
    deployment_files: Dict[str, str]  # devops           (Member 3)  path -> content

    # ------------------------------------------------------------ loop state
    revision_count: int           # Developer rework rounds so far
    # Set when the supervisor gives up on the review/test loop after
    # MAX_REVISIONS and proceeds anyway. review_approved/tests_passed stay
    # an honest reflection of the real verdict (False) — these flags exist
    # ONLY so the supervisor doesn't walk straight back into the same
    # "still not approved/passed" check and loop on itself forever. Reset
    # by the Developer whenever it starts a fresh round of changes.
    review_bypassed: bool
    tests_bypassed: bool

    # ------------------------------------------- post-finish modification loop
    # Optional: after the pipeline first reaches FINISH, the UI can submit a
    # follow-up change request against the finished project. Reuses the
    # existing Developer -> Reviewer -> Tester loop, then pauses at its own
    # HITL gate (modification_approval_node) before re-finishing. Rejecting
    # that gate with feedback starts another round instead of ending it.
    modification_request: str     # pending follow-up change request; "" = none
    modification_pending: bool    # True until the Developer has applied it
    modification_approved: bool   # True once the human approves this round

    # -------------------------------------------------- human-in-the-loop
    approvals: Annotated[List[str], operator.add]  # e.g. ["requirements"]
    human_feedback: str           # filled when the human rejects a stage

    # -------------------------------- collaboration + observability (append)
    agent_messages: Annotated[List[AgentMessage], operator.add]
    logs: Annotated[List[LogEntry], operator.add]
    token_usage: Annotated[Dict[str, Dict[str, float]], merge_usage]
